openapi: 3.1.1
info:
  title: REST API
  version: 0.0.0
  license:
    name: Proprietary
    identifier: Proprietary

servers:
  - url: /api

security:
  - BearerAuth: []

paths:
  /tasks:
    $ref: "./docs/paths/tasks.api.yml"
  /tasks/{id}:
    $ref: "./docs/paths/task.api.yml"

components:
  schemas:
    Task:
      $ref: "./docs/schema/task.yml"
  responses:
    Error400:
      $ref: "./docs/schema/error.yml"
    Error401:
      $ref: "./docs/schema/error.yml"
    Error403:
      $ref: "./docs/schema/error.yml"
    Error404:
      $ref: "./docs/schema/error.yml"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
