openapi: 3.1.1
info:
  title: "REST API"
  version: 0.0.0
  license:
    name: Proprietary
    identifier: Proprietary
servers:
  - url: /api

security:
  - BearerAuth: []

paths:
  /tasks:
    $ref: './docs/paths/tasks.api.yml'
  /task:
    $ref: './docs/paths/task.api.yml'
components:
  schemas:
    Task:
      $ref: './docs/schema/task.yml'
    Error:
        $ref: './docs/schema/error.yml'
    pagination:
      $ref: './docs/pagination/pagination_schema.yml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT